site_name: build-magic
nav:
  - Home: index.md
  - What's New: CHANGELOG.md
  - Getting Started: getting_started.md
  - User Guide:
    - Core Concepts: user_guide/core_concepts.md
    - Using Build-magic: user_guide/basic_usage.md
    - Using the CLI: user_guide/cli_usage.md
    - Defining Config Files: user_guide/config_usage.md
    - Using Command Runners:
      - Using the Local Runner: user_guide/runners/local_usage.md
      - Using the Docker Runner: user_guide/runners/docker_usage.md
      - Using the Vagrant Runner: user_guide/runners/vagrant_usage.md
      - Using the Remote Runner: user_guide/runners/remote_usage.md
  - Comparison with Similar Tools: comparison.md
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid-experimental
  #         format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  # name: readthedocs
  name: material
  palette:
    # scheme: slate
    primary: teal
    accent: light blue
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   primary: teal
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: teal
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
  # highlightjs: true
  # hljs_languages:
  #   - yaml
  #   - bash